apiVersion: taskrun.io/v1alpha1
kind: ClusterStepDefinition
metadata:
  labels:
    app.kubernetes.io/name: taskrun
    app.kubernetes.io/managed-by: kustomize
  name: clusterstepdefinition-sample
spec:
  # TODO(user): Add fields here
