apiVersion: taskrun.io/v1alpha1
kind: ClusterStepDefinition
metadata:
  name: secret-read
spec:
  schema:
    type: object
    required: [secretName, key]
    properties:
      secretName:
        type: string
      key:
        type: string
  outputs:
    - name: value
      description: "The decoded value of the Secret key"
  authAware: false
